apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: container-db
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 123456
              name: MYSQL_DATABASE
              value: snackbar
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
              name: ./src/main/resources/db.migration/init.sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
